[package]
org = "ballerina"
name = "permissions_in_organizations"
version = "0.1.0"
distribution = "2201.8.4"

[[dependency]]
org = "ballerinax"
name = "docusign.dsadmin"
version = "1.0.0"
repository = "local"

[build-options]
observabilityIncluded = true
